/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_18131273_proyecto_03;

import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jose angel
 */
public class PA_18131273_Frame_03a extends javax.swing.JFrame {

    /**
     * Creates new form PA_18131273_Frame_03a
     */
    //Objetos de cada clase sin datos
    Avengers a;
    Flash f ;
    Slenderman s;
    It i;
    DefaultTableModel modelo;//variable para modelo de la tabla
    Pelicula []peliculas = new Pelicula[4];//Arreglo de peliculas
    boolean actualizarPresionado;//variable para evitar mostrar datos nulos
    public PA_18131273_Frame_03a() {
        initComponents();
        this.setLocationRelativeTo(null);// Abir en el centro de la pantalla
        modelo =  (DefaultTableModel)jTableDatos.getModel();//obtener modelo
        modelo.setRowCount(4);//Colocar 4 renglones
        jTableDatos.setShowGrid(true);//mostrar cuadricula
        //Asignar objetos al arreglo
        peliculas[0] =  a =   new Avengers();
        peliculas[1] = f =  new Flash();
        peliculas[2] = s =  new Slenderman();
        peliculas[3] = i =  new It();
        jButMostrar.setEnabled(actualizarPresionado);//Desactivar boton mostrar hasta presionar actualizar
        
    }
    
    public Pelicula[] getInfo(){
        return peliculas;
    }
    
    public void escribirDatos(){          
        for (int r = 0; r < modelo.getRowCount() ; r++) {
            //Escribir datos en comun
              jTableDatos.setValueAt(peliculas[r].getNombre(), r, 0);
              jTableDatos.setValueAt(peliculas[r].getAnio(), r, 1);
              jTableDatos.setValueAt(peliculas[r].getDirector(), r, 2);
              //Compara nombre para escribir atributos propios de cada objeto y cada clase de la que heredan     
              if(jTableDatos.getValueAt(r, 0).equals(f.getNombre())){
                        jTableDatos.setValueAt(f.getSuperHeroe(), r, 3);
                        jTableDatos.setValueAt(f.getActor(), r, 4);
                }
                
              else if(jTableDatos.getValueAt(r, 0).equals(a.getNombre())){
                        jTableDatos.setValueAt(a.getSuperHeroe(), r, 3);
                        jTableDatos.setValueAt(a.getVentas(), r, 4);
                }
                
              else if(jTableDatos.getValueAt(r, 0).equals(s.getNombre() )){
                        jTableDatos.setValueAt(s.getPersonaje(), r, 3);
                        jTableDatos.setValueAt(s.getCompositor(), r, 4);
                }
                
              else if(jTableDatos.getValueAt(r, 0).equals( i.getNombre())){
                        jTableDatos.setValueAt(i.getPersonaje(), r, 3);
                        jTableDatos.setValueAt(i.getAutor(), r, 4);
                }
      
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButActualizar = new javax.swing.JButton();
        jButDesfile = new javax.swing.JButton();
        jButDiagrama = new javax.swing.JButton();
        jButMostrar = new javax.swing.JButton();
        JPanel1 = new java.awt.Panel();
        textArea1 = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        jButEjemplos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FramePrincipal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Año", "Director", "Personaje o Superheroe", "AtributoPropio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 32, 560, 163));

        jButActualizar.setText("Actualizar / Grabar");
        jButActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 150, -1));

        jButDesfile.setText("Desfile");
        jButDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfileActionPerformed(evt);
            }
        });
        getContentPane().add(jButDesfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 88, -1));

        jButDiagrama.setText("Diagrama");
        jButDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDiagramaActionPerformed(evt);
            }
        });
        getContentPane().add(jButDiagrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 100, -1));

        jButMostrar.setText("Mostrar");
        jButMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 80, -1));

        JPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(JPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 205, -1, -1));
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 270, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131273_proyecto_03/Asignacion.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jButEjemplos.setText("Ejemplos");
        jButEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplosActionPerformed(evt);
            }
        });
        getContentPane().add(jButEjemplos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131273_proyecto_03/descripcion.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfileActionPerformed
        PA_18131273_Frame_03b FrameDesfile = new PA_18131273_Frame_03b(this);
        FrameDesfile.setVisible(true);        //mostrar frame de desfile
    }//GEN-LAST:event_jButDesfileActionPerformed

    private void jButDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDiagramaActionPerformed
        new PA_18131273_Frame_03c().setVisible(true);//mostrar frame del diagrama
    }//GEN-LAST:event_jButDiagramaActionPerformed

    private void jButActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButActualizarActionPerformed
        actualizarPresionado = true;//el boton se ha presionado
        for (int r = 0; r < modelo.getRowCount(); r++) {   
             //Comparar atributo superheroe o personaje para asignarselo a su objeto correspondiente y despues al arreglo
              if(jTableDatos.getValueAt(r, 3).equals(f.getSuperHeroe())){
                    f.setNombre(jTableDatos.getValueAt(r, 0)+"");
                    f.setAnio(Integer.parseInt(jTableDatos.getValueAt(r, 1)+""));
                    f.setDirector(jTableDatos.getValueAt(r, 2)+"");
                    peliculas[r] = f;
                }
                
                else if(jTableDatos.getValueAt(r, 3).equals(a.getSuperHeroe())){
                    a.setNombre(jTableDatos.getValueAt(r, 0)+"");
                    a.setAnio(Integer.parseInt(jTableDatos.getValueAt(r, 1)+""));
                    a.setDirector(jTableDatos.getValueAt(r, 2)+"");
                    peliculas[r] = a;
                }
                
              else if(jTableDatos.getValueAt(r, 3).equals( s.getPersonaje() )){
                    s.setNombre(jTableDatos.getValueAt(r, 0)+"");
                    s.setAnio(Integer.parseInt(jTableDatos.getValueAt(r, 1)+""));
                    s.setDirector(jTableDatos.getValueAt(r, 2)+"");
                     peliculas[r] = s;
                }
                
              else if(jTableDatos.getValueAt(r, 3).equals( i.getPersonaje())){
                    i.setNombre(jTableDatos.getValueAt(r, 0)+"");
                    i.setAnio(Integer.parseInt(jTableDatos.getValueAt(r, 1)+""));
                    i.setDirector(jTableDatos.getValueAt(r, 2)+"");
                    peliculas[r] = i;
                }
                jButMostrar.setEnabled(actualizarPresionado);//Activar boton mostrar
                
        }        
    }//GEN-LAST:event_jButActualizarActionPerformed

    private void jButMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMostrarActionPerformed
        for (int i = 0; i < peliculas.length-1; i++) //Ordenar por tamaño nombre de pelicula
            for (int j = i+1; j < peliculas.length ; j++) 
                if (peliculas[i].getNombre().length() < peliculas[j].getNombre().length()){  
                       Pelicula aux = peliculas[i];
                       peliculas[i] = peliculas[j];
                       peliculas[j] = aux;
                }     
        
        escribirDatos();
       
        Component componente = JPanel1;//Obtener componente de pelicula
        int x =100;//x = 100 para dibujar en el centro del panel
        
        //mostrar dibujo mientras se muestra la info
        for (int i = 0; i < 4; i++) { 
            peliculas[i].dibujar(x, componente);
            textArea1.setText(peliculas[i].mostrar());
             try {
            Thread.sleep(3000);//Esperar 3 segundos para la siguiente pelicula
            } catch (InterruptedException ex) {
            Logger.getLogger(PA_18131273_Frame_03a.class.getName()).log(Level.SEVERE, null, ex);
            }          
        }
   
    }//GEN-LAST:event_jButMostrarActionPerformed

    private void jButEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplosActionPerformed
        //datos de ejemplo
        //Avengers
        jTableDatos.setValueAt("Avengers", 0, 0);
        jTableDatos.setValueAt(2012, 0, 1);
        jTableDatos.setValueAt("Joss Whedon", 0, 2);
        jTableDatos.setValueAt("Iron Man", 0, 3);
        jTableDatos.setValueAt("1000000000", 0, 4);
        
        //Flash
        jTableDatos.setValueAt("Flash", 1, 0);    
        jTableDatos.setValueAt(2020, 1, 1);
        jTableDatos.setValueAt("John Francis Daley", 1, 2);
        jTableDatos.setValueAt("Flash", 1, 3);
        jTableDatos.setValueAt("Erza miller", 1, 4);
        
        //Slenderman
        jTableDatos.setValueAt("SlenderMan", 2, 0);
        jTableDatos.setValueAt(2018, 2, 1);
        jTableDatos.setValueAt("Sylvain White", 2, 2);
        jTableDatos.setValueAt("Slender", 2, 3);
        jTableDatos.setValueAt("Brandon campbell", 2, 4);
        
        //It
        jTableDatos.setValueAt("It", 3, 0);
        jTableDatos.setValueAt(1990, 3, 1);
        jTableDatos.setValueAt("Tommy Lee Wallace", 3, 2);  
        jTableDatos.setValueAt("Pennywaise", 3, 3);
        jTableDatos.setValueAt("Stephen King", 3, 4);
                
        
    }//GEN-LAST:event_jButEjemplosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131273_Frame_03a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131273_Frame_03a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel JPanel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButActualizar;
    private javax.swing.JButton jButDesfile;
    private javax.swing.JButton jButDiagrama;
    private javax.swing.JButton jButEjemplos;
    private javax.swing.JButton jButMostrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
